import type {
  ActivityRecord,
  AppUserRecord,
  CaseRecord,
  FinanceTransactionRecord,
  LegalSourceRecord,
  TaskRecord,
  TeamMemberRecord,
} from "@/lib/domain/types";

export const DEMO_TEAM_MEMBERS: TeamMemberRecord[] = [
  {
    id: "u1",
    uid: "JNY-001",
    name: "Shashwat",
    role: "Director, Litigation & Co-Founder",
    type: "mentor",
    loc: "Patna",
    dist: "Patna",
    phone: "8527809671",
    email: "sshashwat8@gmail.com",
    status: "active",
    qual: "BA(H) History, KMC Delhi; LLB, Faculty of Law, University of Delhi",
    join: "2022-01-01",
    bio: "Human rights lawyer and co-founder of Janman People's Foundation. Leads Jan Nyay Abhiyan litigation before Patna High Court and district courts, mentors district fellows.",
  },
  {
    id: "u2",
    uid: "JNY-002",
    name: "Mugdha",
    role: "Lead - Litigation & Research",
    type: "lawyer",
    loc: "Delhi",
    dist: "Patna",
    phone: "9810025572",
    email: "",
    status: "active",
    qual: "BA LLB(Hons), Christ University; LLM, Columbia University",
    join: "2023-06-01",
    bio: "Trial and appellate lawyer with experience in prisoners' rights, post-conviction review and constitutional challenges.",
  },
  {
    id: "u3",
    uid: "JNY-003",
    name: "Shourya Roy",
    role: "Executive Director & Co-Founder",
    type: "admin",
    loc: "Delhi",
    dist: "Patna",
    phone: "",
    email: "",
    status: "active",
    qual: "BA(H) History, KMC Delhi; MSW, DSSW Delhi; PhD pursuing",
    join: "2022-01-01",
    bio: "Social worker and researcher overseeing organisational strategy and programme design.",
  },
  {
    id: "u4",
    uid: "JNY-004",
    name: "Roshin Jacob",
    role: "Legal Fellowship Coordinator",
    type: "coordinator",
    loc: "Patna",
    dist: "Patna",
    phone: "",
    email: "",
    status: "active",
    qual: "BSW, Nirmala Niketan Mumbai; LLB & LLM, St. Joseph's College, Bangalore University",
    join: "2024-07-01",
    bio: "Coordinates the District Legal Fellowship Programme. Guides fellows on case strategy, drafting and hearing preparation.",
  },
  {
    id: "u5",
    uid: "JNY-005",
    name: "Prakash Kumar",
    role: "Lead - Social Work",
    type: "worker",
    loc: "Patna",
    dist: "Patna",
    phone: "",
    email: "",
    status: "active",
    qual: "MSW, Tata Institute of Social Sciences",
    join: "2023-01-01",
    bio: "Senior social work professional heading Jan Nyay's field and community work.",
  },
  {
    id: "u6",
    uid: "JNY-006",
    name: "Sachina",
    role: "District Legal Fellow - Patna",
    type: "fellow",
    loc: "Patna",
    dist: "Patna",
    phone: "",
    email: "",
    status: "active",
    qual: "B.Sc and LLB, Tilka Manjhi University, Bhagalpur",
    join: "2024-10-01",
    bio: "First-generation lawyer from Lakhisarai. Domestic violence, dowry, POCSO, juvenile justice, housing and labour rights.",
  },
  {
    id: "u7",
    uid: "JNY-007",
    name: "Ashwini Pandey",
    role: "Legal Consultant",
    type: "consultant",
    loc: "Purnia",
    dist: "Purnia",
    phone: "",
    email: "",
    status: "active",
    qual: "LLB",
    join: "2024-07-01",
    bio: "Works across Seemanchal trial courts on domestic violence, sexual offences and GBV cases.",
  },
  {
    id: "u8",
    uid: "JNY-008",
    name: "Nawaz Hassan",
    role: "District Legal Fellow - Araria",
    type: "fellow",
    loc: "Araria",
    dist: "Araria",
    phone: "",
    email: "",
    status: "active",
    qual: "LL.B., Aligarh Muslim University",
    join: "2025-01-01",
    bio: "Practicing lawyer in Araria. POCSO, rape, GBV, custodial deaths, unjust eviction and police brutality.",
  },
  {
    id: "u9",
    uid: "JNY-009",
    name: "Tausif Raza",
    role: "District Legal Fellow - Katihar",
    type: "fellow",
    loc: "Katihar",
    dist: "Katihar",
    phone: "",
    email: "",
    status: "active",
    qual: "LL.B., Aligarh Muslim University",
    join: "2025-01-01",
    bio: "Criminal defence advocate, Civil Court Katihar. Prison visits, legal aid camps, PLV trainings, GBV representation.",
  },
  {
    id: "u10",
    uid: "JNY-010",
    name: "Mithlesh Kumar",
    role: "District Legal Fellow - Bhagalpur",
    type: "fellow",
    loc: "Bhagalpur",
    dist: "Bhagalpur",
    phone: "",
    email: "",
    status: "active",
    qual: "LL.B., Tilka Manjhi University",
    join: "2025-01-01",
    bio: "GBV and criminal matters in Bhagalpur courts. Survivor support, complaint filing and documentation.",
  },
  {
    id: "u11",
    uid: "JNY-011",
    name: "Pintu Kumar Mehta",
    role: "District Legal Fellow - Kishanganj",
    type: "fellow",
    loc: "Kishanganj",
    dist: "Kishanganj",
    phone: "",
    email: "",
    status: "active",
    qual: "LL.B., Tilka Manjhi University",
    join: "2025-01-01",
    bio: "Legal awareness and free legal aid for SC/ST, minorities, women and children in Kishanganj.",
  },
  {
    id: "u12",
    uid: "JNY-012",
    name: "Nagmani",
    role: "District Legal Fellow - Purnia",
    type: "fellow",
    loc: "Purnia",
    dist: "Purnia",
    phone: "",
    email: "",
    status: "active",
    qual: "BA LL.B., Bihar Institute of Law, Patna",
    join: "2025-01-01",
    bio: "First-generation lawyer from Purnia. GBV, crimes against minors, welfare scheme access and pro bono representation.",
  },
];

export const DEMO_CASES: CaseRecord[] = [
  {
    id: "c1",
    title: "Rukmani Devi v. State of Bihar",
    client: "Rukmani Devi & Ors",
    respondent: "State of Bihar",
    court: "Patna High Court",
    caseNo: "CWJC 4521/2025",
    firNo: "123/2023",
    section: "Art. 226 Constitution",
    ps: "Kotwali, Purnia",
    type: "Criminal Writ Petition",
    district: "Purnia",
    advocate: "Shashwat",
    worker: "Nagmani",
    status: "active",
    priority: "high",
    facts: "State defaulting on investigation. FIR registered but IO not recording statements u/s 161 CrPC. Key witnesses threatened by accused. No arrest despite cognisable offence.",
    grounds:
      "1. Non-investigation violates Art. 21 - Nilabati Behera v. State of Orissa (1993) 2 SCC 746\n2. Mandatory investigation - Lalita Kumari v. State of UP (2014) 2 SCC 1",
    relief:
      "(a) Direction to constitute SIT; (b) Monthly status reports to HC; (c) Protection to witnesses",
    hearings: [
      {
        id: "h1",
        date: "2025-03-10",
        court: "Patna High Court",
        purpose: "Admission",
        outcome: "Notice issued to State",
        nextDate: "2025-04-20",
        by: "Shashwat",
      },
    ],
    diary: [
      {
        id: "d1",
        date: "2025-03-10",
        action: "Filed Criminal Writ Petition CWJC 4521/2025",
        by: "Shashwat",
        notes: "Petition admitted; interim order for status report from SP",
      },
    ],
    documents: [
      "Writ Petition CWJC 4521/2025",
      "Vakalatnama",
      "FIR Copy 123/2023",
      "Affidavit - Rukmani Devi",
    ],
    createdAt: "2025-03-10",
    updatedAt: "2025-03-15",
  },
  {
    id: "c2",
    title: "Mob Lynching Teghda - Application",
    client: "Mob Lynching Teghda Victims",
    respondent: "State of Bihar",
    court: "District Court, Purnia",
    caseNo: "Cr. App. 089/2024",
    firNo: "45/2024",
    section: "IPC 302, 34",
    ps: "Teghda",
    type: "Application u/s 156(3) CrPC",
    district: "Purnia",
    advocate: "Sachina",
    worker: "Nagmani",
    status: "overdue",
    priority: "high",
    facts: "Mob lynching - FIR filed Sept 2024 but chargesheet not submitted despite 6 months. Victim families receiving threats.",
    grounds:
      "1. Delay in chargesheet violates CrPC 167 - Hussainara Khatoon v. State of Bihar (1979)\n2. Mandatory investigation - Lalita Kumari v. State of UP (2014)",
    relief: "Direction to IO to file chargesheet within 15 days; victim protection order",
    hearings: [
      {
        id: "h2",
        date: "2025-03-28",
        court: "District Court, Purnia",
        purpose: "Appearance",
        outcome: "IO directed to file report",
        nextDate: "2025-04-15",
        by: "Sachina",
      },
    ],
    diary: [
      {
        id: "d2",
        date: "2024-09-01",
        action: "Case opened - FIR registration confirmed",
        by: "Sachina",
        notes: "",
      },
    ],
    documents: [
      "Application u/s 156(3) CrPC",
      "FIR Copy 45/2024",
      "Victim Affidavits (3)",
    ],
    createdAt: "2024-09-01",
    updatedAt: "2025-03-28",
  },
];

export const DEMO_ACTIVITIES: ActivityRecord[] = [
  {
    id: "a1",
    type: "Legal Aid Camp",
    title: "Legal Aid Camp - Ramchak Bariya",
    location: "Ramchak Bariya, Purnia",
    district: "Purnia",
    date: "2025-04-05",
    coordinator: "Sachina",
    conductedBy: ["Sachina", "Nagmani"],
    beneficiaries: 34,
    casesIdentified: 6,
    casesReferred: 2,
    summary:
      "34 beneficiaries attended. Issues: land rights (12), domestic violence (8), MGNREGS wages (7), bonded labour (3).",
    status: "completed",
    followUp: "File representations for 3 MGNREGS cases",
    linkedCases: [],
    participants: [
      {
        id: "ap1",
        activityId: "a1",
        name: "Ramkali Devi",
        phone: "9876543210",
      },
    ],
  },
  {
    id: "a2",
    type: "PLV Training",
    title: "PLV Training - Batch 3",
    location: "Janman Office, Purnia",
    district: "Purnia",
    date: "2025-03-22",
    coordinator: "Shashwat",
    conductedBy: ["Shashwat", "Roshin Jacob"],
    beneficiaries: 12,
    casesIdentified: 0,
    casesReferred: 0,
    summary: "12 youth paralegals trained over 2 days.",
    status: "completed",
    followUp: "Deploy Batch 3 to Teghda and Kasba blocks by April 20",
    linkedCases: [],
    participants: [],
  },
];

export const DEMO_FINANCE_TRANSACTIONS: FinanceTransactionRecord[] = [
  {
    id: "f1",
    date: "2025-04-01",
    type: "grant",
    amount: 2_998_000,
    category: "Top-up Grant",
    project: "DLF Programme",
    description: "APPI Top-up Grant - Addendum 1 (18 months)",
    approvedBy: "Shashwat",
  },
  {
    id: "f2",
    date: "2025-04-02",
    type: "expense",
    amount: 8_500,
    category: "Travel & Boarding",
    project: "DLF Programme",
    description: "Travel to Darbhanga - fact-finding",
    approvedBy: "Shashwat",
  },
  {
    id: "f3",
    date: "2025-04-05",
    type: "expense",
    amount: 5_800,
    category: "Camp/Training Expenses",
    project: "Jan Nyaya Abhiyan",
    description: "Legal Aid Camp - Ramchak Bariya",
    approvedBy: "Sachina",
  },
  {
    id: "f4",
    date: "2025-04-08",
    type: "expense",
    amount: 150_000,
    category: "Salary/Honorarium",
    project: "DLF Programme",
    description: "Fellow honoraria - April 2025 (6 fellows)",
    approvedBy: "Shashwat",
  },
];

export const DEMO_TASKS: TaskRecord[] = [
  {
    id: "t1",
    title: "Prepare brief for Rukmani Devi hearing",
    assignedTo: "Shashwat",
    caseId: "c1",
    deadline: "2025-04-18",
    status: "pending",
    priority: "high",
    notes: "Focus on non-investigation ground; cite Lalita Kumari",
  },
  {
    id: "t2",
    title: "Follow up with Teghda victim family",
    assignedTo: "Sachina",
    caseId: "c2",
    deadline: "2025-04-14",
    status: "pending",
    priority: "high",
    notes: "Confirm whether threats continuing",
  },
];

export function createDemoAdminUsers(seedAdminEmail: string): AppUserRecord[] {
  return [
    {
      id: "admin-1",
      clerkUserId: null,
      email: seedAdminEmail,
      role: "admin",
    },
  ];
}

export const DEMO_LEGAL_SOURCES: LegalSourceRecord[] = [
  {
    id: "ls-1",
    title: "Protection of Women from Domestic Violence Act, 2005",
    documentType: "act",
    jurisdiction: "India",
    issuingAuthority: "Parliament of India",
    citation: "PWDVA, 2005",
    sourceKind: "primary",
    sourceUrl: "",
    status: "current",
    datePublished: null,
    dateEffective: null,
    plainLanguageSummary:
      "Provides protection orders, residence orders, monetary relief, custody directions, compensation, and interim relief for women facing domestic violence.",
    content:
      "Use when the issue involves violence, dispossession from the shared household, economic abuse, threats, stalking, or immediate protection needs. Field follow-up should check immediate safety, contact with a Protection Officer or service provider, the Magistrate forum, and whether interim relief, residence relief, or compensation should be sought.",
    tags: ["domestic violence", "women", "protection order", "residence order", "magistrate"],
    audienceTags: ["district fellows", "lawyers", "social workers"],
    createdAt: "2026-04-12T00:00:00.000Z",
    updatedAt: "2026-04-12T00:00:00.000Z",
  },
  {
    id: "ls-2",
    title: "Scheduled Castes and Scheduled Tribes (Prevention of Atrocities) Act, 1989",
    documentType: "act",
    jurisdiction: "India",
    issuingAuthority: "Parliament of India",
    citation: "SC/ST PoA Act, 1989",
    sourceKind: "primary",
    sourceUrl: "",
    status: "current",
    datePublished: null,
    dateEffective: null,
    plainLanguageSummary:
      "Creates specific offences, investigation safeguards, special courts, relief, and rehabilitation measures for caste-based violence and discrimination.",
    content:
      "Use when facts include caste abuse, social boycott, assault, sexual violence against an SC or ST person, dispossession, forced labour, or obstruction from using public resources. Intake should confirm caste status, FIR stage, safety concerns, medical records, witness threats, and district-level relief or compensation follow-up.",
    tags: ["sc/st", "atrocity", "caste violence", "relief", "special court"],
    audienceTags: ["district fellows", "lawyers", "campaign team"],
    createdAt: "2026-04-12T00:00:00.000Z",
    updatedAt: "2026-04-12T00:00:00.000Z",
  },
  {
    id: "ls-3",
    title: "Bharatiya Nagarik Suraksha Sanhita, 2023 - FIR and arrest safeguards",
    documentType: "rule",
    jurisdiction: "India",
    issuingAuthority: "Parliament of India",
    citation: "BNSS, 2023",
    sourceKind: "primary",
    sourceUrl: "",
    status: "current",
    datePublished: null,
    dateEffective: null,
    plainLanguageSummary:
      "Relevant for police refusal, FIR recording, notice procedures, arrest safeguards, production before magistrates, and early procedural protections in criminal cases.",
    content:
      "Use when the complaint is about police not registering information, refusal to record a cognizable offence, pressure to settle, unlawful custody, or arrest concerns. Drafting should distinguish between zero-FIR style access, representation to supervisory officers, and remedies before the Magistrate when local police do not act.",
    tags: ["fir", "police", "arrest", "criminal procedure", "custody"],
    audienceTags: ["district fellows", "lawyers", "para-legal volunteers"],
    createdAt: "2026-04-12T00:00:00.000Z",
    updatedAt: "2026-04-12T00:00:00.000Z",
  },
  {
    id: "ls-4",
    title: "National Food Security Act and Public Distribution System access",
    documentType: "scheme",
    jurisdiction: "India",
    issuingAuthority: "Government of India and State Food Supply Authorities",
    citation: "NFSA / PDS",
    sourceKind: "primary",
    sourceUrl: "",
    status: "current",
    datePublished: null,
    dateEffective: null,
    plainLanguageSummary:
      "Supports subsidised food grain access for eligible households and helps structure grievances around denial, exclusion, or dealer misconduct.",
    content:
      "Use when ration cards are inactive, names are missing, grain is denied, or dealers are demanding money or refusing supply. Case support should collect ration card details, denial dates, receipts if any, and the relevant block or district supply office path for escalation.",
    tags: ["ration", "pds", "food security", "dealer grievance", "welfare"],
    audienceTags: ["social workers", "district fellows", "campaign team"],
    createdAt: "2026-04-12T00:00:00.000Z",
    updatedAt: "2026-04-12T00:00:00.000Z",
  },
  {
    id: "ls-5",
    title: "Lalita Kumari v. Government of Uttar Pradesh",
    documentType: "case_law",
    jurisdiction: "India",
    issuingAuthority: "Supreme Court of India",
    citation: "Supreme Court of India, 2014",
    sourceKind: "primary",
    sourceUrl: "",
    status: "current",
    datePublished: null,
    dateEffective: null,
    plainLanguageSummary:
      "A leading ruling on mandatory FIR registration for cognizable offences, while allowing limited preliminary inquiry in certain categories.",
    content:
      "Use in drafting or training when the core issue is police refusal to register a cognizable offence, delay in entering information, or the difference between inquiry and investigation. Connect it to field documentation: date of complaint, officer approached, written complaint copy, witness details, and escalation path.",
    tags: ["fir", "supreme court", "police refusal", "cognizable offence", "case law"],
    audienceTags: ["lawyers", "district fellows", "training participants"],
    createdAt: "2026-04-12T00:00:00.000Z",
    updatedAt: "2026-04-12T00:00:00.000Z",
  },
  {
    id: "ls-6",
    title: "Arnesh Kumar v. State of Bihar",
    documentType: "case_law",
    jurisdiction: "India",
    issuingAuthority: "Supreme Court of India",
    citation: "Supreme Court of India, 2014",
    sourceKind: "primary",
    sourceUrl: "",
    status: "current",
    datePublished: null,
    dateEffective: null,
    plainLanguageSummary:
      "A key arrest safeguards ruling that warns against automatic arrests and requires reasoned police action and judicial scrutiny.",
    content:
      "Use when advising teams on arrest-related safeguards, especially in offences where police must justify arrest rather than proceed mechanically. Good for trainings on arrest memos, notice practice, magistrate review, and documenting unlawful detention or intimidation by police.",
    tags: ["arrest", "supreme court", "bihar", "custody", "case law"],
    audienceTags: ["lawyers", "district fellows", "para-legal volunteers"],
    createdAt: "2026-04-12T00:00:00.000Z",
    updatedAt: "2026-04-12T00:00:00.000Z",
  },
  {
    id: "ls-7",
    title: "One Stop Centre and women's emergency response pathway",
    documentType: "notification",
    jurisdiction: "Bihar",
    issuingAuthority: "Women and Child Development support network",
    citation: "OSC / Women Helpline 181",
    sourceKind: "secondary",
    sourceUrl: "",
    status: "current",
    datePublished: null,
    dateEffective: null,
    plainLanguageSummary:
      "Practical emergency pathway for women facing violence, combining shelter, police support, legal aid, counselling, and medical referral.",
    content:
      "Use in field protocols, legal-aid checklists, and training materials when the person needs immediate support rather than only long-form legal analysis. Combine with domestic violence, sexual violence, trafficking, or abandonment scenarios. The emphasis should be safe referral, documenting urgent risk, and quick coordination with district-level support services.",
    tags: ["one stop centre", "181", "women helpline", "referral", "emergency response"],
    audienceTags: ["social workers", "district fellows", "training participants"],
    createdAt: "2026-04-12T00:00:00.000Z",
    updatedAt: "2026-04-12T00:00:00.000Z",
  },
];
